# Generated by Django 5.0.6 on 2024-07-08 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('author_name', models.CharField(max_length=255)),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year_published', models.DateField()),
                ('status', models.CharField(choices=[('B', 'BORROWED'), ('AV', 'AVAILABLE')], default='AV', max_length=6)),
                ('genre', models.CharField(choices=[('R', 'ROMANCE'), ('C', 'COMEDY'), ('A', 'ACTION')], default='R', max_length=10)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('date_borrowed', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='libraryManagement.author')),
            ],
        ),
    ]
