# Generated by Django 5.0.6 on 2024-06-23 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('author_name', models.CharField(max_length=255)),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('date_of_membership', models.DateTimeField(auto_now=True)),
                ('number_of_books_borrowed', models.IntegerField(default=0)),
                ('max_book_limit', models.IntegerField(default=3)),
                ('address', models.CharField(max_length=255)),
                ('is_signed_up', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year_published', models.DateField()),
                ('status', models.CharField(choices=[('B', 'BORROWED'), ('AV', 'AVAILABLE')], default='AV', max_length=6)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('date_borrowed', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='libraryManagement.author')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to='libraryManagement.user')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(related_name='libraries', to='libraryManagement.book')),
                ('users', models.ManyToManyField(related_name='libraries', to='libraryManagement.user')),
            ],
        ),
    ]
