# Generated by Django 5.0.6 on 2024-07-08 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraryManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='library',
            name='books',
            field=models.ManyToManyField(related_name='libraries', to='libraryManagement.book'),
        ),
        migrations.AddField(
            model_name='library',
            name='users',
            field=models.ManyToManyField(related_name='libraries', to=settings.AUTH_USER_MODEL),
        ),
    ]
