# Generated by Django 5.0.6 on 2024-06-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('R', 'ROMANCE'), ('C', 'COMEDY'), ('A', 'ACTION')], default='R', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=256),
        ),
    ]
