# Generated by Django 5.0.6 on 2024-06-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryManagement', '0002_book_genre_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
