# Generated by Django 5.0.6 on 2024-06-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryManagement', '0003_alter_user_password'),
        ('libraryManagement', '0003_book_image'),
    ]

    operations = [
    ]
