# Generated by Django 5.0.6 on 2024-07-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryManagement', '0004_alter_book_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrower',
        ),
    ]
