# Generated by Django 5.0.6 on 2024-07-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_borrowbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowbook',
            old_name='borrowed_at',
            new_name='date_borrowed',
        ),
    ]
